<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-VictorPalermo/blob/main/Treino_de_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
#1
import numpy as np

array = np.zeros(10)

print(array)
print(array.dtype)
print(array.shape)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


In [42]:
#2
import numpy as np

array = np.ones(10)
array_float = array.astype(np.float64)

print(array_float)
print(array_float.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


In [46]:
#3
import numpy as np

array = np.arange(0, 10)

print(array)



[0 1 2 3 4 5 6 7 8 9]
