<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-VictorPalermo/blob/main/Treino_de_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [136]:
import numpy as np

In [137]:
#1
array = np.zeros(10)
print(array)
print(array.dtype)
print(array.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


In [138]:
#2
array = np.ones(10)
array_float = array.astype(np.float64)
print(array_float)
print(array_float.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


In [139]:
#3
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [140]:
#4
array = np.reshape(np.arange(0, 9), (3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [141]:
#5
v = np.array([1,2,0,0,4,0])
print(np.nonzero(v))

(array([0, 1, 4]),)


In [142]:
#6
vetor = np.linspace(0, 1, 12)
print(vetor)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [143]:
#7
matriz = np.eye(5)
print(matriz)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [144]:
#8
rng = np.random.default_rng(42)
array = rng.random((3,3,3))
print(array)

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


In [145]:
#9
matriz = np.random.rand(10,10)
print("min:", matriz.min(), "I max:", matriz.max())

min: 0.01726965696009064 I max: 0.9951739177567773


In [146]:
#10
x = np.array([1,2,3,4,5], dtype=float)
x_normalizado = (x - x.mean()) / x.std()
print(x_normalizado)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [147]:
#11
array = np.array([1,2,3], dtype=np.int32)
array_float32 = array.astype(np.float32)
array_int64 = array_float32.astype(np.int64)
print(array_float32, array_int64)

[1. 2. 3.] [1 2 3]


In [148]:
#12
a = np.array([2,5,7,1,9])
a_clipped = np.clip(a, 0, 5)
print(a_clipped)

[2 5 5 1 5]


In [149]:
#13
vetor = np.arange(10)
vetor_inv = np.flip(vetor)
print(vetor_inv)

[9 8 7 6 5 4 3 2 1 0]


In [150]:
#14
a = np.array([1,2,3])
b = np.array([4,5,6])
hstack = np.hstack((a,b))
vstack = np.vstack((a,b))
print("horizontal:", hstack)
print("vertical:\n", vstack)

horizontal: [1 2 3 4 5 6]
vertical:
 [[1 2 3]
 [4 5 6]]


In [151]:
#15
matriz = np.eye(4) * 5
print(matriz)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [152]:
#16
A = np.arange(12).reshape(3,4)
print("16. Soma linhas:", A.sum(axis=1))
print("16. Soma colunas:", A.sum(axis=0))

16. Soma linhas: [ 6 22 38]
16. Soma colunas: [12 15 18 21]


In [153]:
#17
rng = np.random.default_rng(42)
numeros = rng.integers(0,10,100)
frequencia = np.bincount(numeros, minlength=10)
print(frequencia)

[ 9  9  6  9 15  7 11 15 12  7]


In [154]:
#18
v = np.arange(20)
print(v[1::3])

[ 1  4  7 10 13 16 19]


In [155]:
#19
vetor = np.arange(20)
mask = (v % 2 == 0)
print(v[mask])

[ 0  2  4  6  8 10 12 14 16 18]


In [156]:
#20
lst = [[1,2,3],[4,5,6]]
array = np.array(lst)
print(array, "shape:", array.shape, "dtype:", array.dtype)

[[1 2 3]
 [4 5 6]] shape: (2, 3) dtype: int64


In [157]:
#21
dates = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(dates)

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


In [158]:
#22
A = np.array([[1.,2.,3.],[4.,5.,6.]])
A_centered = A - A.mean(axis=0)
print(A_centered)

[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [159]:
#23
a = np.array([1,2,3])
b = np.array([4,5,6])
print("elemento:", a * b)
print("escalar:", np.dot(a, b))

elemento: [ 4 10 18]
escalar: 32


In [160]:
#24
A = np.arange(12).reshape(3,4)
A[:, [0, 2]] = A[:, [2, 0]]
print(A)

[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


In [161]:
#25
a = np.array([[1, 2], [3, 4]])
b_flat = a.flatten()
b_ravel = a.ravel()
b_ravel[0] = 99
print(a)
print("\n", b_flat)

[[99  2]
 [ 3  4]]

 [1 2 3 4]


In [162]:
#26
board = np.indices((8,8)).sum(axis=0) % 2
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [163]:
#27
x = np.arange(-5, 6)
x2 = np.where(x < 0, 0, x)
print(x2)

[0 0 0 0 0 0 1 2 3 4 5]


In [164]:
#28
rng = np.random.default_rng(0)
data = rng.random(1_000_000)
mean = data.mean()
error = abs(mean - 0.5)
print("Média:", mean, "Erro absoluto:", error)

Média: 0.5001592564636843 Erro absoluto: 0.00015925646368430968


In [165]:
#29
a = np.array([1,2,3])
b = np.array([10,20,30,40])
somas = a[:, None] + b
print(somas)


[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [166]:
#30
from numpy.lib.stride_tricks import sliding_window_view
s = np.array([1, 2, 3, 4, 5])
k = np.array([1, 0, -1])
sw = sliding_window_view(s, k.size)
conv_valid = np.sum(sw * np.flip(k), axis=1)
print("Convolução (valid):", conv_valid)

Convolução (valid): [2 2 2]


In [167]:
#31
A = rng.normal(size=(5,4))
A_min = A.min(axis=0)
A_max = A.max(axis=0)
range_ = np.where(A_max != A_min, A_max - A_min, 1)
A_norm = (A - A_min) / range_
print("Original:\n", A)
print("Normalizado:\n", A_norm)

Original:
 [[ 1.49094907  0.94435386 -0.02251395 -0.13571596]
 [-0.95963055 -0.02685518  1.11267343  0.89208528]
 [ 0.52179943 -0.96786357  0.69747152 -1.57055269]
 [-0.4979807   0.66268666 -1.2872589  -0.4442346 ]
 [ 0.4030978  -0.88356851 -0.67175858  0.08502541]]
Normalizado:
 [[1.         1.         0.52699192 0.58264217]
 [0.         0.49210324 1.         1.        ]
 [0.60452228 0.         0.82699433 0.        ]
 [0.18838394 0.85270127 0.         0.45736243]
 [0.5560841  0.04408236 0.2564657  0.67227831]]


In [168]:
#32
print("32. Ordenar por coluna")
A = np.array([[3,9],[1,4],[2,5]])
idx = np.argsort(A[:,1])
A_sorted = A[idx]
print(A_sorted)

32. Ordenar por coluna
[[1 4]
 [2 5]
 [3 9]]


In [169]:
#33
x = np.array([3,1,2,3,2,3,1])
uniq, first_idx, counts = np.unique(x, return_index=True, return_counts=True)
print("Únicos:", uniq)
print("Primeira ocorrência:", first_idx)
print("Contagens:", counts)

Únicos: [1 2 3]
Primeira ocorrência: [1 2 0]
Contagens: [2 2 3]


In [170]:
#34
P = np.array([[0,0],[3,4],[6,8]])
diff = P[:, None, :] - P[None, :, :]
dist = np.sqrt(np.sum(diff**2, axis=-1))
print(dist)

[[ 0.  5. 10.]
 [ 5.  0.  5.]
 [10.  5.  0.]]


In [171]:
#35
X = rng.normal(size=(1000,3))
cov = np.cov(X, rowvar=False)
corr = np.corrcoef(X, rowvar=False)
print("Covariância:\n", cov)
print("Correlação:\n", corr)

Covariância:
 [[ 1.08607638 -0.05549     0.00456659]
 [-0.05549     1.01136955  0.03083076]
 [ 0.00456659  0.03083076  1.01462456]]
Correlação:
 [[ 1.         -0.05294557  0.0043502 ]
 [-0.05294557  1.          0.03043523]
 [ 0.0043502   0.03043523  1.        ]]


In [172]:
#36
y = np.array([2,0,1,2])
n_classes = y.max() + 1
onehot = np.eye(n_classes)[y]
print(onehot)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [173]:
#37

In [174]:
#38

In [175]:
#39

In [176]:
#40

In [177]:
#41

In [178]:
#42